/*
 * Auto-generated version header for BorASM
 * Generated at compile time from package.json
 * DO NOT EDIT MANUALLY - This file is automatically generated
 */

#ifndef BORASM_VERSION_H
#define BORASM_VERSION_H

#include <string>

namespace BorASM {
namespace Version {

// Version components
constexpr int MAJOR = 0;
constexpr int MINOR = 1;
constexpr int PATCH = 1;
constexpr int BUILD = 163;

// Version strings
constexpr const char* VERSION_STRING = "0.1.1";
constexpr const char* FULL_VERSION_STRING = "0.1.1.163";

// Build information
constexpr const char* BUILD_DATE = "2026-06-12";
constexpr const char* BUILD_TIME = "12:51:17";
constexpr const char* BUILD_YEAR = "2026";

// Git information
constexpr const char* GIT_COMMIT_HASH = "3388639";
constexpr const char* GIT_BRANCH = "develop";
constexpr const char* GIT_DESCRIBE = "3388639";

// Utility functions
inline std::string GetVersionString() {
    return std::string(VERSION_STRING);
}

inline std::string GetFullVersionString() {
    return std::string(FULL_VERSION_STRING);
}

inline std::string GetBuildInfo() {
    return std::string(BUILD_DATE) + " " + std::string(BUILD_TIME);
}

inline std::string GetGitInfo() {
    return std::string(GIT_BRANCH) + "@" + std::string(GIT_COMMIT_HASH);
}

inline std::string GetCompleteVersionInfo() {
    return GetFullVersionString() + " (" + GetGitInfo() + ", built " + GetBuildInfo() + ")";
}

// Version comparison functions
inline bool IsVersionAtLeast(int major, int minor, int patch = 0) {
    if (MAJOR > major) return true;
    if (MAJOR < major) return false;
    if (MINOR > minor) return true;
    if (MINOR < minor) return false;
    return PATCH >= patch;
}

inline bool IsExactVersion(int major, int minor, int patch) {
    return MAJOR == major && MINOR == minor && PATCH == patch;
}

// Development/release detection
#ifdef NDEBUG
constexpr bool IS_RELEASE_BUILD = true;
constexpr const char* BUILD_TYPE = "Release";
#else
constexpr bool IS_RELEASE_BUILD = false;
constexpr const char* BUILD_TYPE = "Debug";
#endif

} // namespace Version
} // namespace BorASM

#endif // BORASM_VERSION_H